import os
import tempfile
import uuid
import torch
import numpy as np
import soundfile as sf
from fastapi import APIRouter, UploadFile, File, Form, HTTPException
from fastapi.responses import FileResponse
from starlette.background import BackgroundTask
from typing import Optional

router = APIRouter()
omni_model = None

@router.post("/omni_tts")
async def omni_tts_handler(
    text: str = Form(...), 
    instruct: Optional[str] = Form(""),
    ref_audio: Optional[UploadFile] = File(None),
    ref_text: Optional[str] = Form(None)
):
    from config import MODELS
    if omni_model is None:
        from omnivoice import OmniVoice
        try:
            model_id = MODELS["omni_voice"]
            print(f"Loading OmniVoice model: {model_id}...")
            device = "mps" if torch.backends.mps.is_available() else ("cuda:0" if torch.cuda.is_available() else "cpu")
            
            omni_model = OmniVoice.from_pretrained(
                model_id,
                device_map=device,
                dtype=torch.float16 if device != "cpu" else torch.float32
            )
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Failed to load OmniVoice model: {str(e)}")

    temp_dir = tempfile.gettempdir()
    file_prefix = os.path.join(temp_dir, f"omni_tts_{uuid.uuid4()}")
    out_file = file_prefix + ".wav"
    ref_path = None
    
    try:
        # OmniVoice 必须有 instruct 参数才能生成自然语音；缺少时使用默认中文风格
        # 只能使用预定义关键词，中文用全角逗号分隔
        default_instruct = "女，青年，中音调"
        effective_instruct = (instruct.strip() if instruct and instruct.strip() else default_instruct)
        kwargs = {"text": text, "instruct": effective_instruct}

        if ref_text and ref_text.strip():
            kwargs["ref_text"] = ref_text.strip()
            
        if ref_audio is not None and ref_audio.size > 0:
            ref_path = os.path.join(temp_dir, f"ref_{uuid.uuid4()}.wav")
            with open(ref_path, "wb") as f:
                f.write(await ref_audio.read())
            kwargs["ref_audio"] = ref_path

        print(f"[OmniTTS] Generating with instruct: {effective_instruct!r}")
        audio_chunks = omni_model.generate(**kwargs)
        
        if not audio_chunks:
            raise ValueError("No audio generated by OmniVoice")

        # 简单输出，不进行额外重采样和指定格式
        sf.write(out_file, audio_chunks[0], getattr(omni_model, 'sample_rate', 16000))

        # 同时保存一份到 data 目录
        import datetime
        import random
        import shutil
        
        data_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data")
        os.makedirs(data_dir, exist_ok=True)
        
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S_%f")[:-3]
        random_num = random.randint(1000, 9999)
        save_path = os.path.join(data_dir, f"{timestamp}_{random_num}.wav")
        
        shutil.copy(out_file, save_path)
        print(f"[OmniTTS] Saved audio copy to: {save_path}")
        
        def cleanup():
            if os.path.exists(out_file): os.remove(out_file)
            if ref_path and os.path.exists(ref_path): os.remove(ref_path)
                
        return FileResponse(
            out_file, 
            media_type="audio/wav", 
            background=BackgroundTask(cleanup)
        )
    except HTTPException:
        raise
    except Exception as e:
        import traceback
        traceback.print_exc()
        if ref_path and os.path.exists(ref_path): os.remove(ref_path)
        if os.path.exists(out_file): os.remove(out_file)
        raise HTTPException(status_code=500, detail=f"OmniVoice TTS error: {str(e)}")
