import os
import tempfile
import uuid
import soundfile as sf
from fastapi import APIRouter, Form
from fastapi.responses import FileResponse
from starlette.background import BackgroundTask
from typing import Optional

router = APIRouter()
vox_model = None

@router.post("/voxcpm")
async def voxcpm_handler(
    text: str = Form(...), 
    instruct: Optional[str] = Form("")
):
    from config import MODELS
    if vox_model is None:
        from voxcpm import VoxCPM
        try:
            model_id = MODELS["vox_cpm"]
            print(f"Loading VoxCPM model: {model_id}...")
            vox_model = VoxCPM.from_pretrained(model_id, load_denoiser=False)
        except Exception as e:
            return {"error": f"Failed to load VoxCPM model: {str(e)}"}

    temp_dir = tempfile.gettempdir()
    out_file = os.path.join(temp_dir, f"voxcpm_{uuid.uuid4()}.wav")
    
    try:
        if instruct and instruct.strip():
            final_text = f"({instruct.strip()}){text}"
        else:
            final_text = text
            
        wav_audio = vox_model.generate(
            text=final_text,
            cfg_value=2.0,
            inference_timesteps=10, 
        )
        
        if wav_audio is None:
            raise ValueError("No audio generated by VoxCPM")
            
        sf.write(out_file, wav_audio, vox_model.tts_model.sample_rate)
        
        # 同时保存一份到 data 目录
        import datetime
        import random
        import shutil
        data_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data")
        os.makedirs(data_dir, exist_ok=True)
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S_%f")[:-3]
        random_num = random.randint(1000, 9999)
        save_path = os.path.join(data_dir, f"{timestamp}_{random_num}.wav")
        shutil.copy(out_file, save_path)
        print(f"[VoxCPM] Saved audio copy to: {save_path}")
        
        return FileResponse(
            out_file, 
            media_type="audio/wav", 
            background=BackgroundTask(os.remove, out_file)
        )
    except Exception as e:
        import traceback
        traceback.print_exc()
        if os.path.exists(out_file): os.remove(out_file)
        return {"error": f"VoxCPM error: {str(e)}"}
